# default: &default
#   adapter: postgresql
#   encoding: unicode
#   username: <%= ENV['POSTGRES_USER'] %>
#   password: <%= ENV['POSTGRES_PASSWORD'] %>
#   pool: 5
#   timeout: 5000
#   host: <%= ENV['POSTGRES_HOST'] %>
# development:
#   <<: *default
#   database: <%= ENV['POSTGRES_DEV_DB'] %>
# test:
#   <<: *default
#   database: <%= ENV['POSTGRES_TEST_DB'] %>
# production:
#   <<: *default
#   database: <%= ENV['POSTGRES_PRODUCTION_DB'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: shoplist_db
  pool: 5
  username: shoplist
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: shoplist_db_test
  pool: 5
  username: shoplist
  password: 